# Disable MSBuild, Use script.
build: off
version: "{build}"

environment:
  COVERALLS_TOKEN:
    secure: yJr/+AGag+h8tNh/4giBRWvveLVKKEXALXK/xjdyHS00pDL12GNVOXynpRllYXd+

init:
  # Add GOPATH/bin and GOROOT/bin to PATH.
  - SET PATH=c:\Users\appveyor\go\bin;c:\go\bin;%PATH%

install:
  - go env
  - go version

test_script:
  - go test -v -coverprofile=coverage.out -covermode=atomic ./...

on_success:
  - go get -v -u github.com/mattn/goveralls
  - goveralls -coverprofile=coverage.out -service=appveyor -repotoken %COVERALLS_TOKEN%
